import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'mr' | 'kn';

type Translations = Record<string, string>;

const translations: Record<Language, Translations> = {
  en: {
    'app.name': 'CIVICSETU',
    'app.tagline': 'Empowering Citizens. Building Better India.',
    'nav.back': 'Back to Home',
    'nav.logout': 'Logout',
    'landing.hero.badge': 'Active Across Multiple Indian States',
    'landing.login.citizen': 'Citizen Login',
    'landing.login.authority': 'Authority Login',
    'landing.login.contractor': 'Contractor Login',
    'landing.login.ngo': 'NGO Login',
    'landing.login.enter': 'Enter Portal',
    'citizen.title': 'Citizen Portal',
    'citizen.tab.issues': 'My Issues',
    'citizen.tab.report': 'Report Issue',
    'citizen.tab.chat': 'Chat',
    'citizen.tab.profile': 'Profile',
    'citizen.report.title': 'Report a New Issue',
    'citizen.report.issueTitle': 'Issue Title',
    'citizen.report.category': 'Category',
    'citizen.report.description': 'Description',
    'citizen.report.address': 'Address',
    'citizen.report.state': 'State',
    'citizen.report.city': 'City',
    'citizen.report.landmark': 'Street / Landmark',
    'citizen.report.image': 'Upload Image (Required)',
    'citizen.report.voiceMode': 'Voice Mode',
    'citizen.report.typeMode': 'Type Mode',
    'citizen.report.submit': 'Submit Issue',
    'citizen.report.voiceHelp': 'Voice complaint feature helps citizens who are not comfortable typing.',
    'citizen.report.startRecord': 'Start Recording',
    'citizen.report.stopRecord': 'Stop Recording',
    'citizen.report.voiceConverted': 'Voice converted successfully!',
    'citizen.report.voiceFailed': 'Voice not clear. Please try again.',
    'citizen.report.recording': 'Recording...',
    'citizen.report.processing': 'Processing voice...',
    'citizen.issues.filter': 'Filter Issues',
    'citizen.issues.all': 'All Issues',
    'citizen.issues.noIssues': 'No issues found.',
    'citizen.vote.up': 'Upvote',
    'citizen.vote.down': 'Downvote',
    'citizen.beforeAfter': 'View Before & After',
    'citizen.status.open': 'Open for Bidding',
    'citizen.status.progress': 'In Progress',
    'citizen.status.resolved': 'Resolved',
    'citizen.status.unresolved': 'Unresolved',
    'citizen.urgency.high': '🔴 High Priority',
    'citizen.urgency.medium': '🟡 Medium Priority',
    'citizen.urgency.low': '🟢 Low Priority',
    'citizen.category.water': 'Water',
    'citizen.category.road': 'Road',
    'citizen.category.electricity': 'Electricity',
    'citizen.category.sanitation': 'Sanitation',
    'citizen.profile.title': 'My Profile',
    'citizen.profile.trustCode': 'Trust Code',
    'citizen.profile.issues': 'Issues Raised',
    'citizen.chat.placeholder': 'Type your message...',
    'citizen.chat.send': 'Send',
    'citizen.issues.viewDetails': 'View Details',
    'citizen.rate.contractor': 'Rate Contractor',
    'citizen.rate.label': 'Rate your experience',
    'citizen.suspicious': '⚠️ Flagged Suspicious',
    'citizen.donate': 'Donate to NGO',
    'select.placeholder': 'Select...',
    'select.state': 'Select State',
    'select.category': 'Select Category',
  },
  hi: {
    'app.name': 'सिविकसेटु',
    'app.tagline': 'नागरिकों को सशक्त बनाना। बेहतर भारत का निर्माण।',
    'nav.back': 'होम पर वापस जाएं',
    'nav.logout': 'लॉग आउट',
    'landing.hero.badge': 'कई भारतीय राज्यों में सक्रिय',
    'landing.login.citizen': 'नागरिक लॉगिन',
    'landing.login.authority': 'प्राधिकरण लॉगिन',
    'landing.login.contractor': 'ठेकेदार लॉगिन',
    'landing.login.ngo': 'एनजीओ लॉगिन',
    'landing.login.enter': 'पोर्टल में प्रवेश करें',
    'citizen.title': 'नागरिक पोर्टल',
    'citizen.tab.issues': 'मेरी समस्याएं',
    'citizen.tab.report': 'समस्या दर्ज करें',
    'citizen.tab.chat': 'चैट',
    'citizen.tab.profile': 'प्रोफ़ाइल',
    'citizen.report.title': 'नई समस्या दर्ज करें',
    'citizen.report.issueTitle': 'समस्या का शीर्षक',
    'citizen.report.category': 'श्रेणी',
    'citizen.report.description': 'विवरण',
    'citizen.report.address': 'पता',
    'citizen.report.state': 'राज्य',
    'citizen.report.city': 'शहर',
    'citizen.report.landmark': 'गली / स्थान',
    'citizen.report.image': 'तस्वीर अपलोड करें (अनिवार्य)',
    'citizen.report.voiceMode': 'आवाज़ मोड',
    'citizen.report.typeMode': 'टाइप मोड',
    'citizen.report.submit': 'समस्या जमा करें',
    'citizen.report.voiceHelp': 'आवाज़ सुविधा उन नागरिकों की मदद करती है जो टाइप करने में असहज हैं।',
    'citizen.report.startRecord': 'रिकॉर्डिंग शुरू करें',
    'citizen.report.stopRecord': 'रिकॉर्डिंग बंद करें',
    'citizen.report.voiceConverted': 'आवाज़ सफलतापूर्वक बदली गई! ✓',
    'citizen.report.voiceFailed': 'आवाज़ स्पष्ट नहीं है। कृपया पुनः प्रयास करें।',
    'citizen.report.recording': 'रिकॉर्डिंग हो रही है...',
    'citizen.report.processing': 'आवाज़ प्रसंस्कृत हो रही है...',
    'citizen.issues.filter': 'समस्याएं फ़िल्टर करें',
    'citizen.issues.all': 'सभी समस्याएं',
    'citizen.issues.noIssues': 'कोई समस्या नहीं मिली।',
    'citizen.vote.up': 'समर्थन करें',
    'citizen.vote.down': 'असमर्थन करें',
    'citizen.beforeAfter': 'पहले और बाद देखें',
    'citizen.status.open': 'बोली के लिए खुला',
    'citizen.status.progress': 'जारी है',
    'citizen.status.resolved': 'हल किया गया',
    'citizen.status.unresolved': 'हल नहीं हुआ',
    'citizen.urgency.high': '🔴 उच्च प्राथमिकता',
    'citizen.urgency.medium': '🟡 मध्यम प्राथमिकता',
    'citizen.urgency.low': '🟢 कम प्राथमिकता',
    'citizen.category.water': 'पानी',
    'citizen.category.road': 'सड़क',
    'citizen.category.electricity': 'बिजली',
    'citizen.category.sanitation': 'स्वच्छता',
    'citizen.profile.title': 'मेरी प्रोफ़ाइल',
    'citizen.profile.trustCode': 'ट्रस्ट कोड',
    'citizen.profile.issues': 'दर्ज की गई समस्याएं',
    'citizen.chat.placeholder': 'अपना संदेश लिखें...',
    'citizen.chat.send': 'भेजें',
    'citizen.issues.viewDetails': 'विवरण देखें',
    'citizen.rate.contractor': 'ठेकेदार को रेट करें',
    'citizen.rate.label': 'अनुभव रेट करें',
    'citizen.suspicious': '⚠️ संदिग्ध रूप से चिह्नित',
    'citizen.donate': 'एनजीओ को दान दें',
    'select.placeholder': 'चुनें...',
    'select.state': 'राज्य चुनें',
    'select.category': 'श्रेणी चुनें',
  },
  ta: {
    'app.name': 'சிவிக்சேது',
    'app.tagline': 'குடிமக்களை வலுப்படுத்துதல். சிறந்த இந்தியாவை கட்டமைத்தல்.',
    'nav.back': 'முகப்புக்கு திரும்பு',
    'nav.logout': 'வெளியேறு',
    'landing.hero.badge': 'பல இந்திய மாநிலங்களில் செயலில் உள்ளது',
    'landing.login.citizen': 'குடிமகன் உள்நுழைவு',
    'landing.login.enter': 'போர்ட்டலில் நுழையுங்கள்',
    'citizen.title': 'குடிமகன் போர்டல்',
    'citizen.tab.issues': 'என் பிரச்சனைகள்',
    'citizen.tab.report': 'பிரச்சனை தெரிவி',
    'citizen.tab.chat': 'அரட்டை',
    'citizen.tab.profile': 'சுயவிவரம்',
    'citizen.report.submit': 'சமர்ப்பி',
    'citizen.status.open': 'ஏலத்திற்கு திறக்கப்பட்டது',
    'citizen.status.progress': 'நடந்து கொண்டிருக்கிறது',
    'citizen.status.resolved': 'தீர்க்கப்பட்டது',
    'citizen.status.unresolved': 'தீர்க்கப்படாதது',
    'citizen.vote.up': 'ஆதரி',
    'citizen.vote.down': 'எதிர்',
    'citizen.beforeAfter': 'முன்பு & பின்பு பார்க்கவும்',
    'citizen.profile.trustCode': 'நம்பிக்கை குறியீடு',
    'citizen.chat.placeholder': 'உங்கள் செய்தியை தட்டச்சு செய்யவும்...',
    'citizen.chat.send': 'அனுப்பு',
    'select.state': 'மாநிலத்தை தேர்ந்தெடு',
    'select.category': 'வகையை தேர்ந்தெடு',
  },
  mr: {
    'app.name': 'सिविकसेटु',
    'app.tagline': 'नागरिकांना सशक्त करणे. चांगले भारत घडवणे.',
    'nav.back': 'मुख्यपृष्ठावर परत',
    'nav.logout': 'लॉग आउट',
    'landing.hero.badge': 'अनेक भारतीय राज्यांमध्ये सक्रिय',
    'landing.login.citizen': 'नागरिक लॉगिन',
    'landing.login.enter': 'पोर्टलमध्ये प्रवेश करा',
    'citizen.title': 'नागरिक पोर्टल',
    'citizen.tab.issues': 'माझ्या समस्या',
    'citizen.tab.report': 'समस्या नोंदवा',
    'citizen.tab.chat': 'संभाषण',
    'citizen.tab.profile': 'प्रोफाइल',
    'citizen.report.submit': 'सबमिट करा',
    'citizen.status.open': 'बोलीसाठी खुले',
    'citizen.status.progress': 'प्रगतीपथावर',
    'citizen.status.resolved': 'सोडवले',
    'citizen.status.unresolved': 'सोडवले नाही',
    'citizen.vote.up': 'समर्थन करा',
    'citizen.vote.down': 'विरोध करा',
    'citizen.beforeAfter': 'आधी आणि नंतर पहा',
    'citizen.profile.trustCode': 'ट्रस्ट कोड',
    'citizen.chat.placeholder': 'तुमचा संदेश लिहा...',
    'citizen.chat.send': 'पाठवा',
    'select.state': 'राज्य निवडा',
    'select.category': 'श्रेणी निवडा',
  },
  kn: {
    'app.name': 'ಸಿವಿಕ್ಸೇತು',
    'app.tagline': 'ನಾಗರಿಕರನ್ನು ಸಶಕ್ತರನ್ನಾಗಿ ಮಾಡುವುದು. ಉತ್ತಮ ಭಾರತ ನಿರ್ಮಿಸುವುದು.',
    'nav.back': 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'landing.hero.badge': 'ಹಲವಾರು ಭಾರತೀಯ ರಾಜ್ಯಗಳಲ್ಲಿ ಸಕ್ರಿಯ',
    'landing.login.citizen': 'ನಾಗರಿಕ ಲಾಗಿನ್',
    'landing.login.enter': 'ಪೋರ್ಟಲ್ ಪ್ರವೇಶಿಸಿ',
    'citizen.title': 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    'citizen.tab.issues': 'ನನ್ನ ಸಮಸ್ಯೆಗಳು',
    'citizen.tab.report': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'citizen.tab.chat': 'ಚಾಟ್',
    'citizen.tab.profile': 'ಪ್ರೊಫೈಲ್',
    'citizen.report.submit': 'ಸಲ್ಲಿಸಿ',
    'citizen.status.open': 'ಬಿಡ್ಡಿಂಗ್‌ಗೆ ಮುಕ್ತ',
    'citizen.status.progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'citizen.status.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    'citizen.status.unresolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ ನಾಹೀ',
    'citizen.vote.up': 'ಬೆಂಬಲಿಸಿ',
    'citizen.vote.down': 'ವಿರೋಧಿಸಿ',
    'citizen.beforeAfter': 'ಮೊದಲು ಮತ್ತು ನಂತರ ನೋಡಿ',
    'citizen.profile.trustCode': 'ಟ್ರಸ್ಟ್ ಕೋಡ್',
    'citizen.chat.placeholder': 'ನಿಮ್ಮ ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
    'citizen.chat.send': 'ಕಳುಹಿಸಿ',
    'select.state': 'ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ',
    'select.category': 'ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const t = (key: string): string => {
    const l = translations[language];
    if (l && l[key]) return l[key];
    return translations.en[key] || key;
  };
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}